version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./path/to/your/symfony/app:/var/www/html
    depends_on:
      - php

  php:
    image: php:7.4-fpm
    volumes:
      - ./path/to/your/symfony/app:/var/www/html

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
